{"name": "Successful login with valid credentials", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114\nCurrent browser version is 128.0.6613.119 with binary path /usr/bin/google-chrome\nStacktrace:\n#0 0x5851373be4e3 <unknown>\n#1 0x5851370edc76 <unknown>\n#2 0x58513711b04a <unknown>\n#3 0x5851371164a1 <unknown>\n#4 0x585137113029 <unknown>\n#5 0x585137151ccc <unknown>\n#6 0x58513715147f <unknown>\n#7 0x585137148de3 <unknown>\n#8 0x58513711e2dd <unknown>\n#9 0x58513711f34e <unknown>\n#10 0x58513737e3e4 <unknown>\n#11 0x5851373823d7 <unknown>\n#12 0x58513738cb20 <unknown>\n#13 0x585137383023 <unknown>\n#14 0x5851373511aa <unknown>\n#15 0x5851373a76b8 <unknown>\n#16 0x5851373a7847 <unknown>\n#17 0x5851373b7243 <unknown>\n#18 0x7ceb12094ac3 <unknown>\n\n", "trace": "  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/login_steps.py\", line 7, in step_impl\n    context.driver = webdriver.Chrome()\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given the user is on the login page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114\nCurrent browser version is 128.0.6613.119 with binary path /usr/bin/google-chrome\nStacktrace:\n#0 0x5851373be4e3 <unknown>\n#1 0x5851370edc76 <unknown>\n#2 0x58513711b04a <unknown>\n#3 0x5851371164a1 <unknown>\n#4 0x585137113029 <unknown>\n#5 0x585137151ccc <unknown>\n#6 0x58513715147f <unknown>\n#7 0x585137148de3 <unknown>\n#8 0x58513711e2dd <unknown>\n#9 0x58513711f34e <unknown>\n#10 0x58513737e3e4 <unknown>\n#11 0x5851373823d7 <unknown>\n#12 0x58513738cb20 <unknown>\n#13 0x585137383023 <unknown>\n#14 0x5851373511aa <unknown>\n#15 0x5851373a76b8 <unknown>\n#16 0x5851373a7847 <unknown>\n#17 0x5851373b7243 <unknown>\n#18 0x7ceb12094ac3 <unknown>\n\n", "trace": "  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/login_steps.py\", line 7, in step_impl\n    context.driver = webdriver.Chrome()\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1725871432226, "stop": 1725871437069}, {"name": "When the user enters valid credentials", "status": "skipped", "start": 1725871437071, "stop": 1725871437071}, {"name": "Then the user should be redirected to the dashboard", "status": "skipped", "start": 1725871437071, "stop": 1725871437071}], "start": 1725871432226, "stop": 1725871437071, "uuid": "5553ae35-03e6-41c1-863a-e079f7d32db9", "historyId": "4b97ba5d6851aa5f87726d66aec9e892", "fullName": "Login functionality: Successful login with valid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}