{"name": "Unsuccessful login with invalid credentials", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114\nCurrent browser version is 128.0.6613.119 with binary path /usr/bin/google-chrome\nStacktrace:\n#0 0x5f3c270714e3 <unknown>\n#1 0x5f3c26da0c76 <unknown>\n#2 0x5f3c26dce04a <unknown>\n#3 0x5f3c26dc94a1 <unknown>\n#4 0x5f3c26dc6029 <unknown>\n#5 0x5f3c26e04ccc <unknown>\n#6 0x5f3c26e0447f <unknown>\n#7 0x5f3c26dfbde3 <unknown>\n#8 0x5f3c26dd12dd <unknown>\n#9 0x5f3c26dd234e <unknown>\n#10 0x5f3c270313e4 <unknown>\n#11 0x5f3c270353d7 <unknown>\n#12 0x5f3c2703fb20 <unknown>\n#13 0x5f3c27036023 <unknown>\n#14 0x5f3c270041aa <unknown>\n#15 0x5f3c2705a6b8 <unknown>\n#16 0x5f3c2705a847 <unknown>\n#17 0x5f3c2706a243 <unknown>\n#18 0x7222da294ac3 <unknown>\n\n", "trace": "  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/login_steps.py\", line 7, in step_impl\n    context.driver = webdriver.Chrome()\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given the user is on the login page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114\nCurrent browser version is 128.0.6613.119 with binary path /usr/bin/google-chrome\nStacktrace:\n#0 0x5f3c270714e3 <unknown>\n#1 0x5f3c26da0c76 <unknown>\n#2 0x5f3c26dce04a <unknown>\n#3 0x5f3c26dc94a1 <unknown>\n#4 0x5f3c26dc6029 <unknown>\n#5 0x5f3c26e04ccc <unknown>\n#6 0x5f3c26e0447f <unknown>\n#7 0x5f3c26dfbde3 <unknown>\n#8 0x5f3c26dd12dd <unknown>\n#9 0x5f3c26dd234e <unknown>\n#10 0x5f3c270313e4 <unknown>\n#11 0x5f3c270353d7 <unknown>\n#12 0x5f3c2703fb20 <unknown>\n#13 0x5f3c27036023 <unknown>\n#14 0x5f3c270041aa <unknown>\n#15 0x5f3c2705a6b8 <unknown>\n#16 0x5f3c2705a847 <unknown>\n#17 0x5f3c2706a243 <unknown>\n#18 0x7222da294ac3 <unknown>\n\n", "trace": "  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/login_steps.py\", line 7, in step_impl\n    context.driver = webdriver.Chrome()\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/home/sujon/Desktop/DevOps_GO/.venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1725877136595, "stop": 1725877137279}, {"name": "When the user enters invalid credentials", "status": "skipped", "start": 1725877137280, "stop": 1725877137280}, {"name": "Then an error message should be displayed", "status": "skipped", "start": 1725877137280, "stop": 1725877137280}], "start": 1725877136594, "stop": 1725877137280, "uuid": "87733b92-11e3-44d3-97a2-d58c17cf2200", "historyId": "0534ab1fb4f268889b47866dd243051b", "fullName": "Login functionality: Unsuccessful login with invalid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}